form styling, validation and handling of course rankings
amir-qayyum-khan/edx-platform pull request #22
Opened 2017-02-05 01:31 UTC by naeem91

form styling, validation and handling of course rankings

2017-02-05 18:30 UTC, wajeeha-khalid commented
@amir-qayyum-khan @naeem91  is it ok if I merge this PR into `jia/registration` branch to get consolidated code at one place?

2017-02-06 05:57 UTC, amir-qayyum-khan commented
if you can test it, then it is ok,
because i havent tested it yet

2017-02-06 06:20 UTC, amir-qayyum-khan commented
@naeem91
- i selected course 2 courses from `Check mark the courses you studied` it is giving me error ``Check mark the courses you studied: Select a valid choice``
- I am getting same error for `Mark the technology you'd like to work on/learn`
- It should allow me as much checkboxes i want to check.
- i think current issue is that we it made all check box required
 
<img width="620" alt="screen shot 2017-02-06 at 11 16 47 am" src="https://cloud.githubusercontent.com/assets/10431250/22636563/fad9594a-ec5d-11e6-9eae-8c6a719026f6.png">
<img width="433" alt="screen shot 2017-02-06 at 11 17 08 am" src="https://cloud.githubusercontent.com/assets/10431250/22636564/fadb9d40-ec5d-11e6-8ec1-0b997f78cfaa.png">

2017-02-06 06:21 UTC, amir-qayyum-khan commented
@naeem91 please add disclaimer to warn students that they can not give exam without filling this form

2017-02-06 06:23 UTC, amir-qayyum-khan commented
Please make the question statement bit prominent, may be you can increase font weight?

<img width="466" alt="screen shot 2017-02-06 at 11 22 27 am" src="https://cloud.githubusercontent.com/assets/10431250/22636643/967c5762-ec5e-11e6-80ab-f74fa1f6e4e2.png">

2017-02-06 06:28 UTC, amir-qayyum-khan requested changes

2017-02-06 06:28 UTC, amir-qayyum-khan commented on common/djangoapps/student/arbisoft/constants.py
>  )
@naeem91 please add new line here

2017-02-06 06:28 UTC, amir-qayyum-khan commented on lms/templates/arbisoft_survey.html
> +                                            ${field.tag()}
what are you doing for other checkbox, 
are you saving others data in [these fields](https://github.com/amir-qayyum-khan/edx-platform/pull/16/files#diff-55b798ee23a7fde8d1103408afcd0f16)? Please explain.

2017-02-06 06:45 UTC, amir-qayyum-khan commented
Radio buttons are so small, can you increase its size
<img width="701" alt="screen shot 2017-02-06 at 11 44 20 am" src="https://cloud.githubusercontent.com/assets/10431250/22637083/af3e8998-ec61-11e6-9f1b-5774d259846e.png">

2017-02-06 06:57 UTC, wajeeha-khalid commented
Why are we using forms for courses and technolgies? should not they be multi-select fields?
It makes sense to use form/formset for ranks as its two dimensional.

2017-02-06 10:09 UTC, merged